### ISSUE TITLE
dssp conda install

### ISSUE THREAD

**Issue by martinpacesa** [salilab/conda-recipes#18] opened 2023-06-14 08:50 UTC
Hello!

I am unable to install dssp with either conda or mamba on python 3.9 or 3.10, it gives an unexpected error or cannot find any dependencies, does it need to be updated?

Thank you!

**Comment by martinpacesa** [comment] 2023-06-14 08:52
`            shell level : 2
       user config file : /home/pacesa/.condarc
 populated config files : /work/lpdi/users/mpacesa/Pipelines/mambaforge/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /work/lpdi/users/mpacesa/Pipelines/mambaforge  (writable)
      conda av data dir : /work/lpdi/users/mpacesa/Pipelines/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/salilab/linux-64
                          https://conda.anaconda.org/salilab/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /work/lpdi/users/mpacesa/Pipelines/mambaforge/pkgs
                          /home/pacesa/.conda/pkgs
       envs directories : /work/lpdi/users/mpacesa/Pipelines/mambaforge/envs
                          /home/pacesa/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1062.52.2.el7.x86_64 rhel/7.7 glibc/2.17
                UID:GID : 255393:10892
             netrc file : None
           offline mode : False`

**Comment by benmwebb** [comment] 2023-06-14 15:57
Duplicate of #16

**Closed by benmwebb** 2023-06-14 15:57 UTC
